# Generated by Django 2.1 on 2019-04-16 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=8)),
                ('picture', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('area', models.TextField(verbose_name='描述')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Star.Star'),
        ),
    ]
