# Generated by Django 2.1 on 2019-04-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Star', '0002_star_hot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tstar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('birthday', models.DateField()),
                ('detail', models.TextField()),
            ],
        ),
    ]
