# Generated by Django 2.1 on 2019-04-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Star', '0003_tstar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('picture', models.ImageField(upload_to='images')),
                ('label', models.CharField(max_length=16)),
            ],
        ),
    ]
