# Generated by Django 2.1 on 2019-04-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Star', '0004_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('yield_time', models.FloatField()),
                ('email', models.CharField(max_length=32)),
            ],
        ),
    ]
